import pandas as pd

df = pd.read_csv(r"..\..\..\CSVCrimenes\Crime_EEUU.csv")

traduccion = {
    "THEFT OF IDENTITY": "Robo de identidad",
    "ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT": "Agresión agravada con arma mortal",
    "THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)": "Robo de vehículo – mayor a $950.01",
    "THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)": "Robo de vehículo – menor a $950",
    "CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)": "Delito contra niño (13 o menos)",
    "VEHICLE - STOLEN": "Vehículo robado",
    "BURGLARY": "Robo con allanamiento",
    "BURGLARY FROM VEHICLE": "Robo desde vehículo",
    "THEFT PLAIN - PETTY ($950 & UNDER)": "Robo menor a $950",
    "INTIMATE PARTNER - SIMPLE ASSAULT": "Agresión simple a pareja",
    "BATTERY - SIMPLE ASSAULT": "Agresión física simple",
    "VANDALISM - MISDEAMEANOR ($399 OR UNDER)": "Vandalismo menor ($399 o menos)",
    "VEHICLE - ATTEMPT STOLEN": "Intento de robo de vehículo",
    "VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)": "Vandalismo grave ($400 o más, todas las iglesias)",
    "ROBBERY": "Robo",
    "FIREARMS RESTRAINING ORDER (FIREARMS RO)": "Orden de restricción de armas de fuego",
    "BIKE - STOLEN": "Bicicleta robada",
    "EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)": "Malversación, gran robo ($950.01 o más)",
    "CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT": "Abuso físico a niño – agresión simple",
    "CRIMINAL THREATS - NO WEAPON DISPLAYED": "Amenazas criminales sin arma",
    "THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD": "Robo mayor a $950.01, excluyendo armas y animales",
    "BATTERY WITH SEXUAL CONTACT": "Agresión con contacto sexual",
    "LETTERS, LEWD  -  TELEPHONE CALLS, LEWD": "Cartas o llamadas telefónicas lascivas",
    "VIOLATION OF COURT ORDER": "Violación de orden judicial",
    "ARSON": "Incendio provocado",
    "VIOLATION OF RESTRAINING ORDER": "Violación de orden de restricción",
    "THEFT, PERSON": "Robo a persona",
    "CONTEMPT OF COURT": "Desacato al tribunal",
    "INTIMATE PARTNER - AGGRAVATED ASSAULT": "Agresión agravada a pareja",
    "ATTEMPTED ROBBERY": "Robo en grado de tentativa",
    "LEWD/LASCIVIOUS ACTS WITH CHILD": "Actos lascivos con menor",
    "OTHER MISCELLANEOUS CRIME": "Otros delitos varios",
    "BRANDISH WEAPON": "Amenazar con arma",
    "TRESPASSING": "Entrada ilegal",
    "BUNCO, ATTEMPT": "Estafa en intento",
    "SHOPLIFTING - PETTY THEFT ($950 & UNDER)": "Robo en tienda menor a $950",
    "BURGLARY, ATTEMPTED": "Intento de robo con allanamiento",
    "DOCUMENT FORGERY / STOLEN FELONY": "Falsificación o robo de documentos",
    "SHOPLIFTING-GRAND THEFT ($950.01 & OVER)": "Robo en tienda mayor a $950.01",
    "FAILURE TO YIELD": "No ceder el paso",
    "BATTERY POLICE (SIMPLE)": "Agresión simple a policía",
    "VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, BIKES, ETC)": "Otros vehículos robados",
    "CHILD NEGLECT (SEE 300 W.I.C.)": "Negligencia infantil",
    "RAPE, ATTEMPTED": "Violación en intento",
    "BUNCO, GRAND THEFT": "Estafa – gran robo",
    "CONTRIBUTING": "Contribuir a delito",
    "PIMPING": "Proxenetismo",
    "OTHER ASSAULT": "Otra agresión",
    "SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH": "Sodomía/contacto sexual",
    "RAPE, FORCIBLE": "Violación forzada",
    "SEX OFFENDER REGISTRANT OUT OF COMPLIANCE": "Infractor sexual fuera de cumplimiento",
    "DISCHARGE FIREARMS/SHOTS FIRED": "Disparo de arma de fuego",
    "EXTORTION": "Extorsión",
    "SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT": "Disparo a vehículo, tren o avión en movimiento",
    "ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER": "Agresión con arma mortal a policía",
    "BUNCO, PETTY THEFT": "Estafa menor",
    "RESISTING ARREST": "Resistencia a la detención",
    "VIOLATION OF TEMPORARY RESTRAINING ORDER": "Violación de orden de restricción temporal",
    "CHILD ANNOYING (17YRS & UNDER)": "Molestar a menor de 17 años",
    "SHOTS FIRED AT INHABITED DWELLING": "Disparo a vivienda ocupada",
    "BURGLARY FROM VEHICLE, ATTEMPTED": "Intento de robo desde vehículo",
    "THROWING OBJECT AT MOVING VEHICLE": "Lanzar objeto a vehículo en movimiento",
    "SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W/ FRGN OBJ": "Sexo ilegal con objeto",
    "ORAL COPULATION": "Copulación oral",
    "SEXUAL PENETRATION W/FOREIGN OBJECT": "Penetración sexual con objeto",
    "LEWD CONDUCT": "Conducta lasciva",
    "PICKPOCKET": "Carterista",
    "CHILD STEALING": "Secuestro de niño",
    "PURSE SNATCHING": "Robo de bolso",
    "THEFT FROM MOTOR VEHICLE - ATTEMPT": "Intento de robo de vehículo",
    "HUMAN TRAFFICKING - COMMERCIAL SEX ACTS": "Trata de personas con fines sexuales",
    "INDECENT EXPOSURE": "Exhibicionismo indecente",
    "DISHONEST EMPLOYEE - PETTY THEFT": "Empleado deshonesto – robo menor",
    "EMBEZZLEMENT, PETTY THEFT ($950 & UNDER)": "Malversación – robo menor a $950",
    "KIDNAPPING": "Secuestro",
    "DISTURBING THE PEACE": "Alteración del orden público",
    "UNAUTHORIZED COMPUTER ACCESS": "Acceso no autorizado a computadora",
    "CRIMINAL HOMICIDE": "Homicidio criminal",
    "THEFT PLAIN - ATTEMPT": "Intento de robo menor",
    "REPLICA FIREARMS(SALE,DISPLAY,MANUFACTURE OR DISTRIBUTE)": "Réplicas de armas – venta, exhibición o fabricación",
    "LYNCHING": "Linchamiento",
    "RECKLESS DRIVING": "Conducción temeraria",
    "THREATENING PHONE CALLS/LETTERS": "Llamadas o cartas amenazantes",
    "SHOPLIFTING - ATTEMPT": "Intento de robo en tienda",
    "BOMB SCARE": "Falsa alarma de bomba",
    "CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT": "Abuso físico a niño – agresión agravada",
    "STALKING": "Acoso",
    "DRIVING WITHOUT OWNER CONSENT (DWOC)": "Conducir sin consentimiento del dueño",
    "BATTERY ON A FIREFIGHTER": "Agresión a bombero",
    "PEEPING TOM": "Espiar",
    "FALSE POLICE REPORT": "Falsa denuncia policial",
    "BOAT - STOLEN": "Barco robado",
    "DEFRAUDING INNKEEPER/THEFT OF SERVICES, $950 & UNDER": "Fraude a hotelero/servicios menor a $950",
    "ILLEGAL DUMPING": "Vertido ilegal",
    "DRUGS, TO A MINOR": "Drogas a menor",
    "THEFT, COIN MACHINE - PETTY ($950 & UNDER)": "Robo de máquina de monedas menor a $950",
    "CREDIT CARDS, FRAUD USE ($950 & UNDER": "Fraude con tarjeta menor a $950",
    "MANSLAUGHTER, NEGLIGENT": "Homicidio culposo",
    "THEFT FROM PERSON - ATTEMPT": "Intento de robo a persona",
    "KIDNAPPING - GRAND ATTEMPT": "Intento de secuestro grave",
    "THEFT, COIN MACHINE - ATTEMPT": "Intento de robo de máquina de monedas",
    "PETTY THEFT - AUTO REPAIR": "Robo menor – taller mecánico",
    "DOCUMENT WORTHLESS ($200 & UNDER)": "Documento sin valor ($200 o menos)",
    "FALSE IMPRISONMENT": "Privación ilegal de libertad",
    "CREDIT CARDS, FRAUD USE ($950.01 & OVER)": "Fraude con tarjeta mayor a $950.01",
    "DEFRAUDING INNKEEPER/THEFT OF SERVICES, OVER $950.01": "Fraude a hotelero/servicios mayor a $950.01",
    "CHILD PORNOGRAPHY": "Pornografía infantil",
    "PANDERING": "Proxenetismo",
    "HUMAN TRAFFICKING - INVOLUNTARY SERVITUDE": "Trata de personas – servidumbre involuntaria",
    "CRUELTY TO ANIMALS": "Crueldad hacia animales",
    "COUNTERFEIT": "Falsificación",
    "DISHONEST EMPLOYEE - GRAND THEFT": "Empleado deshonesto – gran robo",
    "PROWLER": "Merodeador",
    "DOCUMENT WORTHLESS ($200.01 & OVER)": "Documento sin valor ($200.01 o más)",
    "WEAPONS POSSESSION/BOMBING": "Posesión de armas o bombas",
    "GRAND THEFT / AUTO REPAIR": "Gran robo – taller mecánico",
    "CONSPIRACY": "Conspiración",
    "DRUNK ROLL": "Conducción en estado de ebriedad",
    "LYNCHING - ATTEMPTED": "Intento de linchamiento",
    "THEFT, COIN MACHINE - GRAND ($950.01 & OVER)": "Robo de máquina de monedas mayor a $950.01",
    "DISRUPT SCHOOL": "Alteración de la escuela",
    "TILL TAP - PETTY ($950 & UNDER)": "Robo menor de caja registradora ($950 o menos)",
    "PICKPOCKET, ATTEMPT": "Intento de carterismo",
    "GRAND THEFT / INSURANCE FRAUD": "Gran robo / fraude de seguro",
    "TILL TAP - GRAND THEFT ($950.01 & OVER)": "Robo mayor de caja registradora ($950.01 o más)",
    "PURSE SNATCHING - ATTEMPT": "Intento de robo de bolso",
    "BIKE - ATTEMPTED STOLEN": "Intento de robo de bicicleta",
    "BRIBERY": "Soborno",
    "CHILD ABANDONMENT": "Abandono infantil",
    "TELEPHONE PROPERTY - DAMAGE": "Daño a propiedad vía teléfono",
    "BEASTIALITY, CRIME AGAINST NATURE SEXUAL ASSLT WITH ANIM": "Bestialidad, crimen sexual contra animales",
    "BIGAMY": "Bigamia",
    "FAILURE TO DISPERSE": "No dispersarse",
    "FIREARMS EMERGENCY PROTECTIVE ORDER (FIREARMS EPO)": "Orden de protección de emergencia (armas de fuego)",
    "INCEST (SEXUAL ACTS BETWEEN BLOOD RELATIVES)": "Incesto",
    "BLOCKING DOOR INDUCTION CENTER": "Bloqueo de puerta en centro de inducción",
    "INCITING A RIOT": "Incitación a disturbios",
    "DISHONEST EMPLOYEE ATTEMPTED THEFT": "Empleado deshonesto – intento de robo",
    "TRAIN WRECKING": "Sabotaje de tren",
    "DRUNK ROLL - ATTEMPT": "Intento de conducir ebrio"
}

# Crear nueva columna con la traducción
df['Crimen'] = df['Crm Cd Desc'].map(traduccion)

# Mostrar todas las filas
pd.set_option('display.max_rows', None)

# Mostrar todas las columnas
pd.set_option('display.max_columns', None)

# Evitar que se trunque el contenido de cada celda
pd.set_option('display.max_colwidth', None)

# Mostrar las primeras 100 filas de las columnas deseadas
print(df[['Crm Cd Desc', 'Crimen']].head(100))
